### ISSUE TITLE
cannot connect to weblogic server with self signed cert

### ISSUE THREAD

**Issue by Sarkie** [oracle/coherence-visualvm#12]
Cannot connect to weblogic server's management rest API if using a self signed cert.

Please add the ability to ignore certificate errors to the UI

**Comment by Sarkie** [comment]
Works.
Once you enable the checkbox :)
![image](https://user-images.githubusercontent.com/283203/140904609-dd3538d1-954a-4a80-9ba6-c18544202bc2.png)

![image](https://user-images.githubusercontent.com/283203/140904505-549ca647-0562-4f83-a394-6886fb9d2c86.png)

**Comment by tmiddlet2666** [comment]
thanks for validating @Sarkie
