### ISSUE TITLE
Cannot build the latest plugin

### ISSUE THREAD

**Issue by jplaroche-telus** [oracle/coherence-visualvm#83]
**Describe the bug**
Cannot build the plugin

**To Reproduce**
Steps to reproduce the behaviour:
mvn clean install -DskipTest

 **Error in maven**

[INFO] Scanning for projects...
[INFO]
[INFO] ---< com.oracle.coherence.plugin.visualvm:coherence-visualvm-plugin >---
[INFO] Building Coherence VisualVM Plugin Core 1.7.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ nbm ]---------------------------------
[WARNING] The POM for org.graalvm.visualvm.modules:org-graalvm-visualvm-modules-tracer:jar:2.1 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.274 s
[INFO] Finished at: 2024-03-21T20:11:56Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project coherence-visualvm-plugin: Could not resolve dependencies for project com.oracle.coherence.plugin.visualvm:coherence-visualvm-plugin:nbm:1.7.0-SNAPSHOT: The following artifacts could not be resolved: org.graalvm.visualvm.modules:org-graalvm-visualvm-modules-tracer:jar:2.1 (absent): org.graalvm.visualvm.modules:org-graalvm-visualvm-modules-tracer:jar:2.1 was not found in https://oss.sonatype.org/content/groups/staging/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of ossrh-staging has elapsed or updates are forced -> [Help 1]

**Comment by tmiddlet2666** [comment]
hi @jplaroche-telus 
With the addition of the new tracer support in the upcoming release, we need a new dependency which is not yet in maven.
As a workaround, run the following to install this prior to building:
```
scripts/install-tracer-library.sh 
``` 

Once the dep is available this step will no longer be needed.

**Comment by jplaroche-telus** [comment]
Np, built older 1.5.0 tag and now able to use the plugin in VisualVM

**Comment by tmiddlet2666** [comment]
Ok, you can build with main and just run the script above to install the dep.

**Comment by jplaroche-telus** [comment]
Thank you, much appreciated
